const fs = require("fs");
const path = require("path");
const os = require("os");
const JSZip = require("jszip");
const NodeID3 = require("node-id3");
const mm = require("music-metadata");
const ffmpegStatic = require("ffmpeg-static");
const ffmpeg = require("fluent-ffmpeg");

ffmpeg.setFfmpegPath(ffmpegStatic);

async function downloadUrlBuffer(url) {
  if (!url) return null;
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch URL ${url}, status: ${response.status}`);
    }
    const contentType = response.headers.get("content-type") || "";
    const arrayBuffer = await response.arrayBuffer();
    return {
      buffer: Buffer.from(arrayBuffer),
      mimeType: contentType.split(";")[0].trim().toLowerCase(),
    };
  } catch (error) {
    console.error(`Error downloading URL ${url}:`, error);
    return null;
  }
}

async function fetchTrackBuffers(tracks) {
  return Promise.all(
    tracks.map(async (track) => {
      const res = await downloadUrlBuffer(track.url);
      if (!res) {
        throw new Error(`Failed to download audio for track: ${track.title}`);
      }
      return {
        ...track,
        buffer: res.buffer,
      };
    })
  );
}

async function createZipAlbum(book, tracksWithBuffers, coverRes) {
  const zip = new JSZip();
  const coverBuffer = coverRes?.buffer;
  const coverMimeType = coverRes?.mimeType;

  for (const track of tracksWithBuffers) {
    const trackNum = track.trackIndex;
    const padNum = String(trackNum).padStart(2, "0");
    const fileName = `${padNum} - ${track.title.replace(/[^\w\s.\-]/g, "")}.mp3`;

    const tags = {
      title: track.title,
      artist: book.author || "Unknown Author",
      album: book.title || "Unknown Album",
      TPE2: book.author || "Unknown Author",
      genre: "Audiobook",
      year: new Date().getFullYear().toString(),
      trackNumber: `${trackNum}`,
      comment: { language: "eng", text: "Generated by Bookify" },
    };

    if (coverBuffer) {
      tags.image = {
        mime: coverMimeType || "image/png",
        type: { id: 3, name: "front cover" },
        description: "Cover Art",
        imageBuffer: coverBuffer,
      };
    }

    const taggedBuffer = NodeID3.write(tags, track.buffer);
    zip.file(fileName, taggedBuffer);
  }

  return zip.generateAsync({ type: "nodebuffer" });
}

async function createM4bAlbum(book, tracksWithBuffers, coverRes) {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "audiobook-"));
  const tempFiles = [];
  const coverBuffer = coverRes?.buffer;
  const coverMimeType = coverRes?.mimeType;

  try {
    const tracksWithDurations = [];

    for (let i = 0; i < tracksWithBuffers.length; i++) {
      const track = tracksWithBuffers[i];
      const tempMp3Path = path.join(tempDir, `track_${i}.mp3`);
      fs.writeFileSync(tempMp3Path, track.buffer);
      tempFiles.push(tempMp3Path);

      const metadata = await mm.parseFile(tempMp3Path);
      const duration = metadata.format.duration || 0;

      tracksWithDurations.push({
        ...track,
        filePath: tempMp3Path,
        duration,
      });
    }

    const concatFilePath = path.join(tempDir, "concat.txt");
    const concatContent = tracksWithDurations
      .map((t) => `file '${t.filePath.replace(/'/g, "'\\''")}'`)
      .join("\n");
    fs.writeFileSync(concatFilePath, concatContent);
    tempFiles.push(concatFilePath);

    const metadataFilePath = path.join(tempDir, "metadata.txt");
    let metadataContent = ";FFMETADATA1\n";
    metadataContent += `title=${book.title}\n`;
    metadataContent += `artist=${book.author}\n`;
    metadataContent += `album=${book.title}\n`;
    metadataContent += `genre=Audiobook\n`;
    metadataContent += `comment=Generated by Bookify\n\n`;

    let currentOffsetMs = 0;
    for (const track of tracksWithDurations) {
      const durationMs = Math.round(track.duration * 1000);
      metadataContent += "[CHAPTER]\n";
      metadataContent += "TIMEBASE=1/1000\n";
      metadataContent += `START=${currentOffsetMs}\n`;
      metadataContent += `END=${currentOffsetMs + durationMs}\n`;
      metadataContent += `title=${track.title}\n\n`;
      currentOffsetMs += durationMs;
    }
    fs.writeFileSync(metadataFilePath, metadataContent);
    tempFiles.push(metadataFilePath);

    let coverFilePath = "";
    if (coverBuffer) {
      const ext =
        coverMimeType === "image/jpeg" || coverMimeType === "image/jpg"
          ? "jpg"
          : "png";
      coverFilePath = path.join(tempDir, `cover.${ext}`);
      fs.writeFileSync(coverFilePath, coverBuffer);
      tempFiles.push(coverFilePath);
    }

    const outputM4bPath = path.join(tempDir, "output.m4b");

    await new Promise((resolve, reject) => {
      const cmd = ffmpeg();
      cmd.input(concatFilePath).inputOptions(["-f", "concat", "-safe", "0"]);
      cmd.input(metadataFilePath);

      if (coverFilePath) {
        cmd.input(coverFilePath);
      }

      cmd.output(outputM4bPath);

      const outOpts = ["-map", "0:a", "-map_metadata", "1"];

      if (coverFilePath) {
        outOpts.push(
          "-map",
          "2:v",
          "-c:v",
          coverMimeType === "image/jpeg" || coverMimeType === "image/jpg"
            ? "mjpeg"
            : "png",
          "-disposition:v",
          "attached_pic"
        );
      }

      cmd.outputOptions(outOpts);
      cmd.audioCodec("aac");

      cmd.on("end", () => resolve());
      cmd.on("error", (err) => reject(err));
      cmd.run();
    });

    const m4bBuffer = fs.readFileSync(outputM4bPath);
    return m4bBuffer;
  } finally {
    for (const f of tempFiles) {
      try {
        if (fs.existsSync(f)) fs.unlinkSync(f);
      } catch (err) {
        console.error(`Failed to delete temp file ${f}:`, err);
      }
    }
    try {
      if (fs.existsSync(tempDir)) fs.rmdirSync(tempDir);
    } catch (err) {
      console.error(`Failed to remove temp dir ${tempDir}:`, err);
    }
  }
}

module.exports = {
  downloadUrlBuffer,
  fetchTrackBuffers,
  createZipAlbum,
  createM4bAlbum,
};
